apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic
spec:
  count: 1
  elasticsearchRef:
    name: elasticsearch
  podTemplate:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - name: kibana
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
  version: 9.0.0