apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logging-fwd-log-collector-binding
  namespace: elastic
subjects:
- kind: ServiceAccount
  name: logging-fwd
  namespace: elastic
roleRef:
  kind: Role
  name: log-collector-role
  apiGroup: rbac.authorization.k8s.io